### ISSUE TITLE
Usage without a uitableviewcontroller

### ISSUE THREAD

**Issue by mythodeia** [micazeve/MAGearRefreshControl#1]
Thanks for this control!
is there a way i can add it to a uiviewcontroller with a tableview instead of using a uitableviewcontroller?
i tried it but with no luck so far.

**Comment by micazeve** [comment]
Hi,
What is your issue using an UITableView within a UIViewController instead of a UITableViewController ?
The control doesn't use any of the UITableViewController class methods so using a UITableView must produce the same results. Maybe you have forgotten to set the delegate or datasource of the table view in your code. I've updated the sample project in order to show you how to use it with a UITableView.

**Comment by mythodeia** [comment]
first of all thanks for your reply.
i am trying to use your control in an obj-c project by the way....
this is what i am seeing when i scroll the tableview
its like the gears are not populated. and it crashes because arrayViews is out of bounds (its empty)

![demo](https://cloud.githubusercontent.com/assets/1748458/9576764/a137c6c8-4fe3-11e5-9ef3-8de2fd1dbd1e.png)

**Comment by mythodeia** [comment]
@micazeve 
never mind my friend...i found it. i did not include the addInitialGearWithNbTeeth at all. now it works fine.
thanks
